name = "UnfoldMixedModels"
uuid = "019ae9e0-8363-565c-86e5-97a5a2fe84f4"
authors = ["Benedikt Ehinger <benedikt.ehinger@vis.uni-stuttgart.de>"]
version = "0.1.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"

[compat]
DataFrames = "1"
DocStringExtensions = "0.9"
LinearAlgebra = "1"
MixedModels = "4, 5"
ProgressMeter = "1"
Reexport = "1"
SimpleTraits = "0.9"
SparseArrays = "1"
StaticArrays = "1"
StatsAPI = "1"
StatsModels = "0.7"
Unfold = "0.8"
julia = "1"
